# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeFirestore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeFirestore
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'ReactNativeFirestoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeFirestore-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeFirestore-tvOS

  target 'ReactNativeFirestore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
